# Generated by Django 5.2.6 on 2025-09-20 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("album", models.CharField(max_length=100)),
                ("bpm", models.IntegerField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_choice",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Reason"
                    ),
                ),
                (
                    "one_line_review",
                    models.TextField(
                        blank=True, null=True, verbose_name="One line review"
                    ),
                ),
                (
                    "recommendation_theme",
                    models.TextField(
                        blank=True, null=True, verbose_name="Recommendation theme"
                    ),
                ),
                (
                    "feeling",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Feeling"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "review_text",
                    models.TextField(blank=True, null=True, verbose_name="Review text"),
                ),
                (
                    "achievement",
                    models.TextField(
                        blank=True, null=True, verbose_name="Archievement"
                    ),
                ),
                (
                    "significance",
                    models.TextField(
                        blank=True, null=True, verbose_name="Significance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="jazzclub.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("vocal", "보컬"),
                            ("composer", "작곡"),
                            ("lyricist", "작사"),
                            ("performer", "연주"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "deleted_at",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist",
                        to="jazzclub.artist",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="jazzclub.song",
                    ),
                ),
            ],
            options={
                "unique_together": {("song", "artist", "role")},
            },
        ),
    ]
