# Generated by Django 5.2.6 on 2025-09-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jazzclub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Is Deleted"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Is Deleted"
            ),
        ),
        migrations.AlterField(
            model_name="songartist",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Is Deleted"
            ),
        ),
        migrations.AlterField(
            model_name="songreview",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Is Deleted"
            ),
        ),
    ]
