# Generated by Django 5.2.6 on 2025-09-20 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jazzclub", "0002_alter_artist_deleted_at_alter_song_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="composers",
            field=models.JSONField(
                blank=True, default=list, verbose_name="작곡가 ID들"
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="lyricists",
            field=models.JSONField(
                blank=True, default=list, verbose_name="작사가 ID들"
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="performers",
            field=models.JSONField(
                blank=True, default=list, verbose_name="연주자 ID들"
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="vocalists",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[1, 2, 3] 형태의 아티스트 ID 리스트",
                verbose_name="보컬 아티스트 ID들",
            ),
        ),
        migrations.AlterField(
            model_name="songreview",
            name="achievement",
            field=models.TextField(blank=True, null=True, verbose_name="Achievement"),
        ),
        migrations.AlterUniqueTogether(
            name="songreview",
            unique_together={("song", "user")},
        ),
        migrations.DeleteModel(
            name="SongArtist",
        ),
    ]
