# Generated by Django 5.2.6 on 2025-09-16 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "book_title",
                    models.CharField(max_length=200, verbose_name="Book Title"),
                ),
                (
                    "book_author",
                    models.CharField(max_length=200, verbose_name="Book Author"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1점"),
                            (2, "2점"),
                            (3, "3점"),
                            (4, "4점"),
                            (5, "5점"),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "read_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Read Date"
                    ),
                ),
                (
                    "discussion_topic",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Discussion Topic"
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="Tags"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Review",
                "ordering": ["-created_at"],
            },
        ),
    ]
