# Generated by Django 5.2.6 on 2025-09-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookreview", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bookreview",
            table="bookreview",
        ),
    ]
